// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-rZS_U6Sph6IpnIHWYHRcwyQcbY_NRjo',
    appId: '1:453008319062:web:31e51ce0b057f4d27dd1f7',
    messagingSenderId: '453008319062',
    projectId: 'crud-48da6',
    authDomain: 'crud-48da6.firebaseapp.com',
    storageBucket: 'crud-48da6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Lhn4PmsQT7cPS7d2c44Ie_yQmqAnYGg',
    appId: '1:453008319062:android:1902538dd77edf8c7dd1f7',
    messagingSenderId: '453008319062',
    projectId: 'crud-48da6',
    storageBucket: 'crud-48da6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_dfHtWsbkRLW9XImZXXrxssHqyRppaA',
    appId: '1:453008319062:ios:07d579ab435575f67dd1f7',
    messagingSenderId: '453008319062',
    projectId: 'crud-48da6',
    storageBucket: 'crud-48da6.appspot.com',
    iosClientId: '453008319062-n9h5b50tu1uofhvm92mvd2chduu6f1qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_dfHtWsbkRLW9XImZXXrxssHqyRppaA',
    appId: '1:453008319062:ios:07d579ab435575f67dd1f7',
    messagingSenderId: '453008319062',
    projectId: 'crud-48da6',
    storageBucket: 'crud-48da6.appspot.com',
    iosClientId: '453008319062-n9h5b50tu1uofhvm92mvd2chduu6f1qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
